### PR TITLE
feat: add GenerateKeyRaw method in order to save the raw bytes for encrypt without the piv device

### PR DESCRIPTION
**Pull request by izouxv**
feat: add GenerateKeyRaw method in order to save the raw bytes for encrypt, and set DecodePublic to public for parse the raw bytes

### CODE REVIEW

**Comment by ericchiang** [comment]
Hey, thanks for the PR! Can you elaborate on why you need this? Is it for a public key type this package doesn't support, or some other reason?

**Comment by izouxv** [comment]
> Hey, thanks for the PR! Can you elaborate on why you need this? Is it for a public key type this package doesn't support, or some other reason?

 save the pub key for encrypt something without piv device.

**Comment by ericchiang** [comment]
@izouxv you should already be able to serialize the key with encodings like https://pkg.go.dev/crypto/x509#MarshalPKIXPublicKey

That works fine without this package exposing the raw public key or parsing logic

**Comment by izouxv** [comment]
> @izouxv you should already be able to serialize the key with encodings like https://pkg.go.dev/crypto/x509#MarshalPKIXPublicKey
> 
> That works fine without this package exposing the raw public key or parsing logic

thank you

**Pull request closed without merging**
